### 获取当前用户模型信息列表
GET http://localhost:8081/api/model/list
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NzAyODUzMjQsImV4cCI6MTc3MDM3MTcyNH0.ylvDCPD9PFPcfQKkxybKC3rbfIfMarHYVJVnWIuqLVSoVD2JG1vljJwqt5YOa7-_0FexK2N9eScdARMWCufAQQ

### 管理员获取平台全部用户的所有模型信息
GET http://localhost:8081/api/model/all
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NzAyODUzMjQsImV4cCI6MTc3MDM3MTcyNH0.ylvDCPD9PFPcfQKkxybKC3rbfIfMarHYVJVnWIuqLVSoVD2JG1vljJwqt5YOa7-_0FexK2N9eScdARMWCufAQQ

