### 创建数据分析任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjIzMzI4MzgsImV4cCI6MTc2MjQxOTIzOH0.DAy9Y_ntHuA-AR05e6jRWcJXQLhK3RB3dxysEVkD-XstE9RbUjr1DPPFQ34dBp3LOLHgwcurpVo-mspuzZ-09A

{
  "datasetId": 1,
  "taskType": 0,
  "clusterCount": 0,
  "forecastSteps": 0
}

### 创建用户聚类任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjE4MDg0ODAsImV4cCI6MTc2MTg5NDg4MH0.cMebPs_KTr2OuER_HkJy22GB0Y_fpDxYbVlHnELoOgQRujhV0vKgdok0-JjeOT7X3HxTZdf3m4dJWOkPuEH38w

{
  "datasetId": 1,
  "taskType": 1,
  "clusterCount": 2,
  "forecastSteps": 0
}

### 创建负荷预测任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjIsInN1YiI6IjIiLCJpYXQiOjE3NjQzMTk3NDIsImV4cCI6MTc2NDQwNjE0Mn0.UBf83xxryMTBFoaJi-shaGsNaVhaCx1ByrBCe9jbvD3U2GSZPRgE355SQ7CrGaaozjWxv3-HaKqTzqHh5KUbcw

{
  "datasetId": 6,
  "taskType": 2,
  "clusterCount": 0,
  "forecastSteps": 5
}

### 获取当前用户的所有任务信息
GET http://localhost:8081/api/task/list
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjQsInN1YiI6IjQiLCJpYXQiOjE3NjkwNzQ3ODAsImV4cCI6MTc2OTE2MTE4MH0.W5350eqZH2Pwi6aMO_FleACMNr5lbOolQ_fsnvr7x9GAbgCLYLeg36kQyBZBDsWi1f0utEj3tsuI7qNJjck2Ow

### 管理员获取平台全部用户的所有任务信息
GET http://localhost:8081/api/task/all
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjQsInN1YiI6IjQiLCJpYXQiOjE3NjkwNzQ3ODAsImV4cCI6MTc2OTE2MTE4MH0.W5350eqZH2Pwi6aMO_FleACMNr5lbOolQ_fsnvr7x9GAbgCLYLeg36kQyBZBDsWi1f0utEj3tsuI7qNJjck2Ow
