### 创建数据分析任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjE1MzMzOTAsImV4cCI6MTc2MTYxOTc5MH0.DMbNIxDdmi5jqCnGoXYlgz-X9AXgApm1vgUkNECUfRqa0YsPORJLX3wP0S2E-956xt4vogqK6nLonpt6Tv743A

{
  "datasetId": 1,
  "taskType": 0,
  "clusterCount": 0,
  "forecastSteps": 0
}

### 创建用户聚类任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjExMDYzMDEsImV4cCI6MTc2MTE5MjcwMX0.wQPRjFAKIyyTYqBt41UrT-r5QAtzUI03r8h933_1X-4issC5Zu_ZIs8L-LlfqBviP-a1lN79yn9wl32DvEWhG7A

{
  "datasetId": 1,
  "taskType": 1,
  "clusterCount": 3,
  "forecastSteps": 0
}

### 创建负荷预测任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjExMDYzMDEsImV4cCI6MTc2MTE5MjcwMX0.wQPRjFAKIyTYqBt41UrT-r5QAtzUI03r8h933_1X-4issC5Zu_ZIs8L-LlfqBviP-a1lN79yn9wl32DvEWhG7A

{
  "datasetId": 1,
  "taskType": 2,
  "clusterCount": 0,
  "forecastSteps": 7
}
