### 用户注册
POST http://localhost:8081/api/user/register
Content-Type: application/json

{
  "username": "testuser3",
  "password": "password123"
}

### 用户登录
POST http://localhost:8081/api/user/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

### 获取用户个人信息（需要登录）
GET http://localhost:8081/api/user/profile
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjE1Mjg0MzQsImV4cCI6MTc2MTYxNDgzNH0.ii_SQefyB7-4p4eHue4JDm3_wITnZC3fsyRiMiOszAz6KHA1s_QfBFQ5031i-Q_9kcW4Uqrt8n9Xxeoi9IXX4w

### 上传用户头像（需要登录）
POST http://localhost:8081/api/user/avatar
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjEwOTM5ODUsImV4cCI6MTc2MTE4MDM4NX0.l2wspW_XyhH5FTpnNpbEvmhwYYecK4n-lohVeezJRqQUoH494WqCAGIGPU8t4vV-evxKZcyRzgdWU_wAue4h3g
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="p7.png"

< C:\Users\25064\Desktop\temp\p7.png
--WebAppBoundary--

### 获取用户头像URL（需要登录）
GET http://localhost:8081/api/user/avatar-url
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjEwNTk1NDksImV4cCI6MTc2MTE0NTk0OX0.wSFEqJrbf6KgcSFNf88ODLu7os_mDaz3gExNdLwLA6TQogD5XZujAgTCaaxYk6OSvC5tI-9W5x40de_0bsBXqg

