### 用户注册1

POST http://localhost:8081/api/user/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

### 用户注册2

POST http://localhost:8081/api/user/register
Content-Type: application/json

{
  "username": "testuser3",
  "password": "password123"
}

### 用户登录

POST http://localhost:8081/api/user/login
Content-Type: application/json

{
  "username": "testuser3",
  "password": "password123"
}

### 获取用户个人信息（需要登录）
GET http://localhost:8081/api/user/profile
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjMsInN1YiI6IjMiLCJpYXQiOjE3NjA2MjgzMzQsImV4cCI6MTc2MDcxNDczNH0.-axjhNTEIxhJAJKKEz-7yxF5jYBsnabmKCPHs-DZaJzpBw6Qu9inY4JJ4tujX5jf5nUg-v2rfKb5PuBchUX6sA
