### 创建数据分析任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjE4MDg0ODAsImV4cCI6MTc2MTg5NDg4MH0.cMebPs_KTr2OuER_HkJy22GB0Y_fpDxYbVlHnELoOgQRujhV0vKgdok0-JjeOT7X3HxTZdf3m4dJWOkPuEH38w

{
  "datasetId": 1,
  "taskType": 0,
  "clusterCount": 0,
  "forecastSteps": 0
}

### 创建用户聚类任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjE4MDg0ODAsImV4cCI6MTc2MTg5NDg4MH0.cMebPs_KTr2OuER_HkJy22GB0Y_fpDxYbVlHnELoOgQRujhV0vKgdok0-JjeOT7X3HxTZdf3m4dJWOkPuEH38w

{
  "datasetId": 1,
  "taskType": 1,
  "clusterCount": 2,
  "forecastSteps": 0
}

### 创建负荷预测任务
POST http://localhost:8081/api/task/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsInN1YiI6IjEiLCJpYXQiOjE3NjE4MDg0ODAsImV4cCI6MTc2MTg5NDg4MH0.cMebPs_KTr2OuER_HkJy22GB0Y_fpDxYbVlHnELoOgQRujhV0vKgdok0-JjeOT7X3HxTZdf3m4dJWOkPuEH38w

{
  "datasetId": 1,
  "taskType": 2,
  "clusterCount": 0,
  "forecastSteps": 5
}
