tickTime=2000
dataDir=D:/ONLY_ENGLISH_DIR/projects/power-load-assessment-260809/runtime/zookeeper-data
clientPort=2181
maxClientCnxns=0
admin.enableServer=false
autopurge.snapRetainCount=3
autopurge.purgeInterval=1
